Update index.md
btcguide/btcguide.github.io pull request #78
Opened 2021-01-18 01:09 UTC by MinimalStructure

I added a Trezor Wallet explanation and an Option C: Blue Wallet for the Emergency Recovery

2021-01-18 05:23 UTC, mflaxman requested changes
Thanks for the PR! I like the general direction, but I don't think we should recommend the Trezor One. Advanced users can probably figure it out, but given that it's already stateless (!) the substitution cipher is non-ideal. And the model T has an SD car that's not used for signing, but if they add support for it in the future it could make the Trezor less bad at multisig.

Also, the spellchecker is failing. Please fix misspellings and update `wordlist.txt` to add words to the spellchecker.

2021-01-18 05:23 UTC, mflaxman commented on _pages/emergency-recovery/index.md
> +7. To enter our seed into the device, you will navigate the scrambled BIP39 wordlist on our Trezor.  In this example I will enter “zoo” 23 times and “buddy” one time. The screen says, “Select letters
You skipped `6.`, but actually it's easiest/best to make everything `1.` and jekyll will auto-increment.

2021-01-18 05:23 UTC, mflaxman commented on _pages/emergency-recovery/index.md
> +Our device also says, “Please enter the 1st word of you mnemonic” and it gives us groups of scrambled letters.  These letters correspond with the 9 keys on our number pad.  In this example:
This is pretty confusing, perhaps we should (for now) only recommend the Model T. It's still stateless, but it at least has a "keyboard" on the touchscreen which doesn't require a substitution cipher.

2021-01-18 05:23 UTC, mflaxman commented on _pages/emergency-recovery/index.md
> +3. Blue Wallet is an open-source wallet available on the App Store, Google Play, APK and Desktop for macOS. It is free, readily available and easy to use. **As it will be touching private key materia
Misspelled works

2021-01-18 05:23 UTC, mflaxman commented on _pages/emergency-recovery/index.md
> +5. 1. Download Blue Wallet from the Appstore, Google Play or the [bluewallet.io](https://bluewallet.io/).
What's with the numbering here?

2021-01-18 05:23 UTC, mflaxman commented on _pages/emergency-recovery/index.md
> +1. TODO Add screen shots and a video
Is there a link to a video/tutorial anywhere?

2021-01-18 08:37 UTC, holgern commented
There must be no newline inbetween a list, otherwise pandoc will not handle them correctly. Please remove all line breaks such that it looks like:
```
1. ...
1. ...
1. ...
```

2021-01-28 01:06 UTC, MinimalStructure commented
Back to the drawing board :)

I noticed Blue Wallet only let's users import keys while connected to the Internet.

That's a bad idea.

It could work in an extreme emergency, but  it's not good enough for the guide.

2021-01-28 04:25 UTC, mflaxman commented
Oh bummer, unfortunate they don't support an airgap :(

Closing for now, please reopen/edit if you disagree.

2021-01-28 04:25 UTC, closed without merging